apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: book-admin-role
  namespace: bookstore-microservices
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources:
      - endpoints
      - services
      - pods
    verbs:
      - list
      - get
      - watch