kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway
  namespace: bookstore-microservices
data:
  application.yaml: |-
    spring:
      cloud:
        gateway:
          routes:
            - id: account
              uri: http://account
              predicates:
                - Path=/restful/accounts/**
            - id: payment
              uri: http://payment
              predicates:
                - Path=/restful/pay/**
            - id: settlement
              uri: http://payment
              predicates:
                - Path=/restful/settlements/**
            - id: advertisements
              uri: http://warehouse
              predicates:
                - Path=/restful/advertisements/**
            - id: products
              uri: http://warehouse
              predicates:
                - Path=/restful/products/**
            - id: security
              uri: http://security
              predicates:
                - Path=/oauth/**

    server:
      port: ${PORT:8080}

    logging:
      level:
        root: INFO
