apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-microservices-domain-warehouse
  namespace: bookstore-microservices
  labels:
    app: warehouse
spec:
  replicas: 1 # Consider increasing for production
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      containers:
        - name: warehouse
          image: icyfenix/bookstore-kubernetes-domain-warehouse
          imagePullPolicy: IfNotPresent # Added for clarity and control
          ports:
            - name: http-server
              containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources: # Added resource requests and limits
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: config-volume
          configMap:
            name: warehouse
